config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	resources :jankens do
		collection do
			get 'tables'
			get 'battle'
		end
	end
	root 'jankens#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

	private
  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up , keys: [:name, :ticket, :text])
	end
end

app/controllers/jankens_controller.rb
class JankensController < ApplicationController
	def index
	end

	def tables
		@users = User.all.shuffle
		@total_users = User.all
	end

	def battle
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jankens_helper.rb
module JankensHelper
end

app/views/jankens/battle.html.haml
%main
	.main__left
		.character
		%div{style: "text-align: center; font-size:30px;"} YOU!
		.selects
			%ul
				.selects__content
					.selects__image-r
					.hands
						%li#gu_btn グー
				.selects__content
					.selects__image-s
					.hands
						%li#cho_btn チョキ
				.selects__content
					.selects__image-p
					.hands
						%li#par_btn パー
	.main__right
		.character__oponent
		%div{style: "text-align: center; font-size:30px;"} JEDI
		.selects
			%ul
				.selects__content
					.selects__image-r
				.selects__content
					.selects__image-s
				.selects__content
					.selects__image-p
			#pc.hand
	#message
	.text__box
		ジャンケン...
		%br
		%br
		#result{style: "font-size:40px; text-align:center; color:red;"}

app/views/jankens/index.html.haml
.text
	Welcome To Ruby Janken Contest!!!
	.img
		=image_tag "rails.jpg"
.list
	%ul
	-if user_signed_in?
		%li
			=link_to "Sign_out", destroy_user_session_path, method: :delete
	-else
		%li
			.box
				=link_to "Sign_up",new_user_registration_path,{style: "text-decoration: none;"}
		%li
			.box
				=link_to "Sign_in",new_user_session_path,{style: "text-decoration: none;"}
		%li
			.box
				=link_to "Play" ,tables_jankens_path,{style: "text-decoration: none;"}

app/views/jankens/tables.html.haml
.content
	.content__main
		.text
			%span{style: "text-align: center;"} Hello Everyone!!!!
		.content__table
			%table
				%tr
					%th 順番
					%th	名前
					%th	チケット数
					%th	メッセージ
				-@users.each_with_index do |user,index|
					%tr
						%td
							= index + 1
						%td
							=user.name
						%td
							=user.ticket
						%td
							=user.text
			%button
				=link_to "Start",battle_jankens_path,method: :get
	.balloon
		%p 参加人数は#{@total_users.count}人だね。チケットは全部で#{@total_users.sum(:ticket)}枚!
		%p ゲームを始めるよ！！
	.img__character
		=image_tag "Octocat.png"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Janken
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{:src => "janken.js", :type => "text/javascript"}
  %body{style: "margin:0;"}
    = yield